spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: "D!ck3n5@123"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  security:
    user:
      name: dickens
      password: 12345678

server:
  port: 8081
