server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: D!ck3n5@!@#
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

